---
exec_module: 'noop'
bilara_root_path: "~/bilara-data/root/pli/ms"

pali_canon_path: "~/ms_palicanon"
bilara_html_path: ""
bilara_comment_path: ""
bilara_variant_path: ""
bilara_translation_path: ""
ms_yuttadhammo_path: ""
pali_concordance_filepath: "~/all_pali_concordance.json"

# Path where check_migration script result will be saved.
# It should point to the migration_differences folder in the Bilara-data project.
migration_differences_path: ""

reference_root_path: "~/reference/pli/ms"
exclude_filepath: ""

debug_dir: ""
# Log level: [0, 50]. 10-debug, 20-info
log_level: 20
